#!/bin/bash
# =============================================================================
# AUTO-GENERATED FIRMWARE TEST SCRIPT
# Generated by: generate_test_from_firmware.sh
# Generated at: Fri Mar  6 10:38:06 IST 2026
# Firmware   : v5.48
# SYSTEM     : 2
# UNIT       : SPATIKA_GEN
# Station ID : WS0034
#
# !! DO NOT EDIT THIS FILE MANUALLY !!
# !! Regenerate with: ./generate_test_from_firmware.sh !!
# =============================================================================

STATION_ID="WS0034"
HTTP_URL="http://rtdas.spatika.net:80/tws_gprs/twsrf_gen"
FTP_SERVER="ftp.spatika.net"
FTP_USER="twsrf_gen"
FTP_PASS="spgen123"

SLOT_CSV="2026-03-06,10:30"
BACKLOG_CSV="2026-03-06,09:30"

echo "============================================================"
echo " Firmware Test | v5.48 | SPATIKA_GEN | SYSTEM=2"
echo " Station: $STATION_ID"
echo " HTTP: $HTTP_URL"
echo " FTP : $FTP_SERVER"
echo " Time: Current=$SLOT_CSV  Backlog=$BACKLOG_CSV"
echo "============================================================"

PASS=0
FAIL=0

run_test() {
    local label="$1"
    local url="$2"
    local payload="$3"
    local content_type="$4"
    local response

    if [ "$content_type" = "application/json" ]; then
        response=$(curl -s -m 10 -X POST -H "Content-Type: application/json" -d "$payload" "$url")
    else
        response=$(curl -s -m 10 -X POST -d "$payload" "$url")
    fi

    if echo "$response" | grep -qi "success\|ok\|stored"; then
        echo "  ✅ $label: $response"
        PASS=$((PASS+1))
    else
        echo "  ❌ $label: $response"
        FAIL=$((FAIL+1))
    fi
}

# ── HTTP: Current Slot ────────────────────────────────────────────────────────
echo ""
echo "[A] HTTP — Current Slot ($SLOT_CSV)"
PAYLOAD_CUR="stn_id=${STATION_ID}&rec_time=${SLOT_CSV}&key=wsgen2014&rainfall=00.00&temp=028.5&humid=060.0&w_speed=00.25&w_dir=180&signal=-063&bat_volt=03.9&bat_volt2=03.9"
run_test "Current HTTP" "$HTTP_URL" "$PAYLOAD_CUR" "application/x-www-form-urlencoded"

# ── HTTP: Backlog slot (1 hour old) ──────────────────────────────────────────
echo ""
echo "[B] HTTP — Backlog Slot ($BACKLOG_CSV)"
PAYLOAD_OLD="stn_id=${STATION_ID}&rec_time=${BACKLOG_CSV}&key=wsgen2014&rainfall=01.00&temp=029.0&humid=058.0&w_speed=00.50&w_dir=90&signal=-075&bat_volt=03.8&bat_volt2=03.8"
run_test "Backlog HTTP" "$HTTP_URL" "$PAYLOAD_OLD" "application/x-www-form-urlencoded"

# ── FTP: Connectivity Check ───────────────────────────────────────────────────
echo ""
echo "[C] FTP — Connection Check (passive login test)"
FTP_RESULT=$(curl -s -m 15 --ftp-pasv     "ftp://ftp.spatika.net/"     --user "twsrf_gen:spgen123"     --list-only 2>&1 | head -5)
if echo "$FTP_RESULT" | grep -qiE "^[0-9]|\.txt|\.swd|\.kwd|\.csv|ftp"; then
    echo "  ✅ FTP Login OK: $FTP_RESULT"
    PASS=$((PASS+1))
else
    echo "  ❌ FTP Login FAILED: $FTP_RESULT"
    FAIL=$((FAIL+1))
fi

# ── FTP: Dummy File Upload ────────────────────────────────────────────────────
echo ""
echo "[D] FTP — Dummy File Upload"
DUMMY_FILE="/tmp/ftp_test_$(date +'%Y%m%d_%H%M%S').swd"
printf "%s\r\n" \
    "WS0034;2026-03-06,10:30;00.00;028.5;060.0;00.25;180;-063;03.9" \
    "WS0034;2026-03-06,09:30;01.00;029.0;058.0;00.50;090;-075;03.8" > "$DUMMY_FILE"
UPLOAD_RESULT=$(curl -s -m 20 --ftp-pasv     "ftp://ftp.spatika.net/$(basename $DUMMY_FILE)"     --user "twsrf_gen:spgen123"     --upload-file "$DUMMY_FILE" 2>&1)
if [ $? -eq 0 ]; then
    echo "  ✅ FTP Upload OK: $(basename $DUMMY_FILE)"
    PASS=$((PASS+1))
    # Cleanup uploaded test file
    curl -s -m 10 "ftp://ftp.spatika.net/" --user "twsrf_gen:spgen123" -Q "DELE $(basename $DUMMY_FILE)" > /dev/null 2>&1
    echo "     (Test file auto-deleted from FTP server)"
else
    echo "  ❌ FTP Upload FAILED: $UPLOAD_RESULT"
    FAIL=$((FAIL+1))
fi
rm -f "$DUMMY_FILE"


# ── Health Report ─────────────────────────────────────────────────────────────
echo ""
echo "[E] Health Report"
HEALTH_URL="http://75.119.148.192:80/health"
HEALTH_PAYLOAD="{\"stn_id\":\"${STATION_ID}\",\"unit_type\":\"SPATIKA_GEN\",\"system\":2,\"health_sts\":\"OK\",\"sensor_sts\":\"RTC-OK,SPIFFS-OK\",\"reset_reason\":5,\"rtc_ok\":1,\"uptime_hrs\":12,\"bat_v\":3.9,\"sol_v\":0.0,\"signal\":-63,\"reg_fails\":0,\"reg_avg\":1.0,\"reg_worst\":1,\"reg_fail_type\":\"none\",\"http_fails\":0,\"http_fail_reason\":\"none\",\"http_avg\":1.2,\"net_cnt\":10,\"net_cnt_prev\":10,\"ndm_cnt\":0,\"pd_cnt\":0,\"cdm_sts\":\"OK\",\"first_http\":1,\"spiffs_kb\":584,\"spiffs_total_kb\":4640,\"sd_sts\":\"FAIL\",\"calib\":\"NONE\",\"ver\":\"5.48\",\"carrier\":\"BSNL\",\"iccid\":\"89917190324927658487\",\"gps\":\"13.004021,77.549263\",\"ota_fails\":0,\"ota_fail_reason\":\"none\"}"
HEALTH_RESP=$(curl -s -m 10 -X POST -H "Content-Type: application/json" -d "$HEALTH_PAYLOAD" "$HEALTH_URL")
echo "  Health Response: $HEALTH_RESP"
if echo "$HEALTH_RESP" | grep -qi "ok\|success\|received\|stored"; then
    echo "  ✅ Health Report: OK"
    PASS=$((PASS+1))
else
    echo "  ⚠️  Health Report: Unexpected response (may still be OK)"
fi

# ── Final Result ──────────────────────────────────────────────────────────────
echo ""
echo "============================================================"
echo " Results: ✅ $PASS passed | ❌ $FAIL failed"
echo "============================================================"
if [ $FAIL -gt 0 ]; then
    exit 1
fi
